[package]

name = "atomic-option"
version = "0.1.2"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/rust-atomic-option.git"
description = "An atomic, nullable, owned pointer."
readme = "README.md"
license = "MIT"

